# This is a basic workflow that is manually triggered
name: Market prediction inference pipeline

on:
  workflow_dispatch:
    inputs:
      step_id:
        description: "step_id is the first step to start with"
        default: 0
        required: true
        type: int

  #push:
  #  # Sequence of patterns matched against refs/tags
  #  tags:
  #    - 'smp-lgbm-v*' # Push events to matching smp-v*, i.e. smp-v1.0, smp-v20.15.10

env:
  MODEL_VERSION: smp-lgbm-v0.11
  MODEL_NAME: s5-mod-lgbm
  FEATURE_VERSION: smp-fe-v0.02
  FEATURE_TYPE: v1

jobs:

  s6-mod-lgbm-pred:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh

    - name: Download features
      run: |
        wget https://github.com/haroldmei/ml-automation/releases/download/$FEATURE_VERSION/s3-fe-$FEATURE_TYPE.tar.gz > /dev/null
        tar xf s3-fe-$FEATURE_TYPE.tar.gz
        mv s3-fe-$FEATURE_TYPE output
        ls output

    - name: Download model
      run: |
        wget https://github.com/haroldmei/ml-automation/releases/download/$MODEL_VERSION/$MODEL_NAME.zip > /dev/null
        unzip $MODEL_NAME.zip
        mv $MODEL_NAME/models output
        ls output

    - name: execute py script, s6-mod-lgbm-pred
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        python models/lgbm.py --pred
        mkdir -p data/models
        cp -rf output/models/* data/models

    - uses: actions/upload-artifact@v4
      with:
        name: s6-mod-lgbm-pred
        path: data/


  s7-mod-lgbm-bt:
    runs-on: ubuntu-latest
    needs: [s6-mod-lgbm-pred]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh

    - name: Download model
      run: |
        wget https://github.com/haroldmei/ml-automation/releases/download/$MODEL_VERSION/$MODEL_NAME.zip > /dev/null
        unzip $MODEL_NAME.zip
        mv $MODEL_NAME output

    - name: execute py script, s7-mod-lgbm-bt
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        python backtest/bt.py
        mkdir -p data/models
        cp -rf output/models/* data/models

    - uses: actions/upload-artifact@v4
      with:
        name: s7-mod-lgbm-bt
        path: data/


  release:
    name: Release Models
    needs: [s7-mod-lgbm-bt]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: actions/download-artifact@v4
      with:
        name: s7-mod-lgbm-bt
        path: s7-mod-lgbm-bt/

    - name: Build project # This would actually build your project, using zip for an example artifact
      run: |
        ls s7-mod-lgbm-bt/
        zip -r s7-mod-lgbm-bt.zip s7-mod-lgbm-bt/

    - name: Create Release
      id: create_prediction
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_SSH_KEY }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
        
    - name: Upload Release Asset s7-mod-lgbm-bt
      id: upload-release-asset-s7-mod-lgbm-bt
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PRIVATE_SSH_KEY }}
      with:
        upload_url: ${{ steps.create_prediction.outputs.upload_url }} #
        asset_path: ./s7-mod-lgbm-bt.zip
        asset_name: s7-mod-lgbm-bt.zip
        asset_content_type: application/zip