# This is a basic workflow that is manually triggered
name: Stock market prediction modelling

on:
  workflow_dispatch:
    inputs:
      step_id:
        description: "step_id is the first step to start with"
        default: 0
        required: true
        type: int

jobs:
  s1-yf-ingest:
    if: ${{ inputs.step_id }} <= ${{ 1 }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh

    - name: execute py script, download yf data
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        python etl/yf.py
    - uses: actions/upload-artifact@v4
      with:
        name: s1-yf-ingest
        path: output/

  s2-fe-ta:
    if: ${{ inputs.step_id }} <= ${{ 2 }}
    needs: s1-yf-ingest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh

    - name: install talib
      run: |
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/ && sudo ./configure && sudo make && sudo make install && pip install ta-lib && cd ..
    - uses: actions/download-artifact@v4
      with:
        name: s1-yf-ingest
        path: output/
    - name: execute py script, s2-fe-ta
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        #gsutil cp gs://hmei-bucket-us/market-prediction/output.tar.gz ./
        #tar xf output.tar.gz
        python features/fe_ta.py
    - uses: actions/upload-artifact@v4
      with:
        name: s2-fe-ta
        path: output/
    
  s3-fe-v1:
    if: ${{ inputs.step_id }} <= ${{ 3 }}
    needs: s2-fe-ta
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh
    - uses: actions/download-artifact@v4
      with:
        name: s2-fe-ta
        path: output/
    - name: execute py script, s3-fe-v1
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        #gsutil cp gs://hmei-bucket-us/market-prediction/output.tar.gz ./
        #tar xf output.tar.gz
        python features/fe_v1.py
        python features/fe_knn.py
    - uses: actions/upload-artifact@v4
      with:
        name: s3-fe-v1
        path: output/

  s3-fe-v2:
    if: ${{ inputs.step_id }} <= ${{ 3 }}
    needs: s2-fe-ta
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh
    - uses: actions/download-artifact@v4
      with:
        name: s2-fe-ta
        path: output/
    - name: execute py script, s3-fe-v2
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        #gsutil cp gs://hmei-bucket-us/market-prediction/output.tar.gz ./
        #tar xf output.tar.gz
        python features/fe_v2.py
        python features/fe_knn.py
    - uses: actions/upload-artifact@v4
      with:
        name: s3-fe-v2
        path: output/
    
  s4-mod-lgbm-cv-v1:
    if: ${{ inputs.step_id }} <= ${{ 4 }}
    needs: s3-fe-v1
    strategy:
      matrix:
        reg_alpha: [-1, 0, 1]
        reg_lambda: [-1, 0, 1]
        min_data_in_leaf: [-1, 0, 1]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh
    - uses: actions/download-artifact@v4
      with:
        name: s3-fe-v1
        path: output/
    - name: execute py script, s4-mod-lgbm-v1
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        python models/lgbm.py --cv --reg_alpha=${{ matrix.reg_alpha }} --reg_lambda=${{ matrix.reg_lambda }} --min_data_in_leaf=${{ matrix.min_data_in_leaf }}
    - uses: actions/upload-artifact@v4
      with:
        name: s4-mod-lgbm-cv-v1
        path: output/

  s4-mod-lgbm-cv-v2:
    if: ${{ inputs.step_id }} <= ${{ 4 }}
    needs: s3-fe-v2
    strategy:
      matrix:
        reg_alpha: [-1, 0, 1]
        reg_lambda: [-1, 0, 1]
        min_data_in_leaf: [-1, 0, 1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh
    - uses: actions/download-artifact@v4
      with:
        name: s3-fe-v2
        path: output/
    - name: execute py script, s4-mod-lgbm-v2
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        python models/lgbm.py --cv --reg_alpha=${{ matrix.reg_alpha }} --reg_lambda=${{ matrix.reg_lambda }} --min_data_in_leaf=${{ matrix.min_data_in_leaf }}
    - uses: actions/upload-artifact@v4
      with:
        name: s4-mod-lgbm-cv-v2
        path: output/

  s5-mod-lgbm-v1:
    if: ${{ inputs.step_id }} <= ${{ 5 }}
    needs: s4-mod-lgbm-cv-v1

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh
    - uses: actions/download-artifact@v4
      with:
        name: s4-mod-lgbm-cv-v1
        path: output/
    - name: execute py script, s4-mod-lgbm-v1
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        python models/lgbm.py --epochs=50
    - uses: actions/upload-artifact@v4
      with:
        name: s5-mod-lgbm-v1
        path: output/

  s5-mod-lgbm-v2:
    if: ${{ inputs.step_id }} <= ${{ 5 }}
    needs: s4-mod-lgbm-cv-v2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh
    - uses: actions/download-artifact@v4
      with:
        name: s4-mod-lgbm-cv-v2
        path: output/
    - name: execute py script, s4-mod-lgbm-v2
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        python models/lgbm.py --epochs=50
    - uses: actions/upload-artifact@v4
      with:
        name: s5-mod-lgbm-v2
        path: output/

  s4-mod-ae-v1:
    #if: ${{ inputs.step_id }} <= ${{ 4 }}
    if: False
    needs: s3-fe-v1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh tensorflow==2.10.1 tensorflow-probability==0.14.0 keras==2.10.0
    - uses: actions/download-artifact@v4
      with:
        name: s3-fe-v1
        path: output/
    - name: execute py script, s4-mod-ae-v1
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        #gsutil cp gs://hmei-bucket-us/market-prediction/fe_v1/output.tar.gz ./
        #tar xf output.tar.gz
        python models/ae.py --cv
        python models/ae.py --epochs=50
        python models/ae.py --pred
    - uses: actions/upload-artifact@v4
      with:
        name: s4-mod-ae-v1
        path: output/

  s4-mod-ae-v2:
    #if: ${{ inputs.step_id }} <= ${{ 4 }}
    if: False
    needs: s3-fe-v2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "haroldmei/stock-market-prediction"
        token: ${{ secrets.PRIVATE_SSH_KEY }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - name: Install Packages and Python dependencies
      run: |
        python -m pip install --upgrade pip pandas joblib yfinance==0.2.28 matplotlib numpy scipy vectorbt PyPortfolioOpt seaborn lightgbm scikit-learn tsfresh tensorflow==2.10.1 tensorflow-probability==0.14.0 keras==2.10.0
    - uses: actions/download-artifact@v4
      with:
        name: s3-fe-v2
        path: output/
    - name: execute py script, s4-mod-ae-v2
      run: |
        export PYTHONPATH=/home/runner/work/ml-automation/ml-automation/
        #gsutil cp gs://hmei-bucket-us/market-prediction/fe_v2/output.tar.gz ./
        #tar xf output.tar.gz
        python models/ae.py --cv
        python models/ae.py --epochs=50
        python models/ae.py --pred
    - uses: actions/upload-artifact@v4
      with:
        name: s4-mod-ae-v2
        path: output/

  conclude:
    needs: [s5-mod-lgbm-v1, s5-mod-lgbm-v2]
    runs-on: ubuntu-latest
    steps:
    - name: Conclude here
      run: lscpu; lsmem; echo "Finished scraping ${{ inputs.parameter_1 }}"